var ref=[
{"race":501,"desc":"Twin River Casino"},
{"race":502,"desc":"Newport Grand"},
{"race":503,"desc":"Higher Education Facilities"},
{"race":504,"desc":"Veterans Home Bonds"},
{"race":505,"desc":"Clean Water Bonds"},
{"race":506,"desc":"Environmental Management Bonds"},
{"race":507,"desc":"Capital ImprovementS"},
{"race":705,"desc":"Capital improvements"},
{"race":706,"desc":"Playgrounds and athletic fields"},
{"race":707,"desc":"Merge fire district into town"},
{"race":708,"desc":"Charter amendment, town administrator"},
{"race":709,"desc":"Charter amendment, term of office"},
{"race":710,"desc":"Charter amendment, town clerk"},
{"race":711,"desc":"Charter amendment, appointments and tenure"},
{"race":712,"desc":"Charter amendment, town clerk"},
{"race":713,"desc":"Charter amendment, Department of Education"},
{"race":714,"desc":"Charter amendment, recall provision"},
{"race":721,"desc":"Charter amendments"},
{"race":722,"desc":"Purchasing policy"},
{"race":723,"desc":"Council officers"},
{"race":724,"desc":"Budget preparation"},
{"race":725,"desc":"Air quality, energy improvements"},
{"race":726,"desc":"School roof repairs, replacements"},
{"race":727,"desc":"High school fire systems"},
{"race":728,"desc":"Coventry High athletic renovations"},
{"race":729,"desc":"HVAC improvements at schools"},
{"race":730,"desc":"School grounds flooring improvements"},
{"race":731,"desc":"Fiscal year defined"},
{"race":732,"desc":"Charter amendment, budget"},
{"race":733,"desc":"Charter amendment, department consolidation"},
{"race":734,"desc":"Charter amendment, 4-year terms"},
{"race":736,"desc":"Charter amendment, composition, election etc."},
{"race":737,"desc":"Charter amendment, independent audit"},
{"race":738,"desc":"Charter amendment, election supervision"},
{"race":739,"desc":"Charter amendment, lapse of appropriation"},
{"race":740,"desc":"Charter amendment, land use tax"},
{"race":741,"desc":"Charter amendment, 4-year term"},
{"race":742,"desc":"Capital improvements, roads"},
{"race":743,"desc":"Capital improvement, open space"},
{"race":744,"desc":"Casino gaming - Lincoln"},
{"race":745,"desc":"Renovations to Fire Department etc."},
{"race":746,"desc":"Charter amendment, council power"},
{"race":747,"desc":"Charter amendment, personnel review board"},
{"race":748,"desc":"Charter amendment, lost wages"},
{"race":749,"desc":"Charter amendment, collective bargaining"},
{"race":750,"desc":"Charter amendment, collective bargaining agreements"},
{"race":751,"desc":"Road and sidewalk improvements"},
{"race":752,"desc":"Charter amendment, Town Council"},
{"race":753,"desc":"Charter amendment, elections "},
{"race":754,"desc":"Charter amendment, Fire Department"},
{"race":755,"desc":"Charter amendment, boards and committees"},
{"race":756,"desc":"Charter amendment, inauguration, succession"},
{"race":757,"desc":"Charter amendment, code of ethics"},
{"race":758,"desc":"Charter amendment, town positions"},
{"race":759,"desc":"Charter amendment, language changes"},
{"race":760,"desc":"Casino gambling - Newport"},
{"race":761,"desc":"Charter amendment, term limits"},
{"race":762,"desc":"Charter amendment, council noninterference"},
{"race":763,"desc":"Charter amendment, School Committee"},
{"race":764,"desc":"Charter amendment, budget"},
{"race":765,"desc":"Charter amendment, review committees"},
{"race":766,"desc":"Charter amendment, council proceedings"},
{"race":767,"desc":"Charter amendment, administrator's report"},
{"race":768,"desc":"Charter amendment, town engineer"},
{"race":769,"desc":"Charter amendment, public works director"},
{"race":770,"desc":"Charter amendment, parks recreation"},
{"race":771,"desc":"Charter amendment, personnel"},
{"race":772,"desc":"Charter amendment, Planning Board"},
{"race":773,"desc":"Charter amendment, administrator/personnel"},
{"race":774,"desc":"Charter amendment, budget submittal month"},
{"race":775,"desc":"Charter amendment, budget transmittal day"},
{"race":776,"desc":"Charter amendment, budget public hearings"},
{"race":777,"desc":"Charter amendment, petition signature validity"},
{"race":778,"desc":"Charter amendment, fund budget submittal"},
{"race":779,"desc":"Charter amendment, enterprise fund budgets"},
{"race":780,"desc":"Charter amendment, School Committee budget"},
{"race":781,"desc":"At-large council"},
{"race":782,"desc":"Council terms"},
{"race":783,"desc":"Term limits"},
{"race":784,"desc":"Council compensation"},
{"race":785,"desc":"Mayoral term limit"},
{"race":786,"desc":"Recall"},
{"race":787,"desc":"Even-year elections"},
{"race":788,"desc":"Residency"},
{"race":789,"desc":"Council vacancies"},
{"race":790,"desc":"Construction of streets, sidewalks"},
{"race":791,"desc":"Construction of sewer, sanitation"},
{"race":792,"desc":"Traffic-control devices"},
{"race":793,"desc":"Bridge reconstruction"},
{"race":794,"desc":"Public recreation facilities"},
{"race":795,"desc":"Renovation of public buildings"},
{"race":796,"desc":"Renovations, public schools"},
{"race":797,"desc":"Street and sidewalk improvements"},
{"race":798,"desc":"Charter amendment, defined terms"},
{"race":799,"desc":"Charter amendment, review commissions"},
{"race":800,"desc":"Charter amendment approvals"},
{"race":801,"desc":"Charter amendment, personnel/HR department"},
{"race":802,"desc":"Charter amendment, HR enforcement"},
{"race":803,"desc":"Charter amendment, HR responsibilities"},
{"race":804,"desc":"Charter amendment, public property director qualifications"},
{"race":805,"desc":"Charter amendment, emergency management/homeland"},
{"race":806,"desc":"Charter amendment, city employment"},
{"race":807,"desc":"Charter amendment, ward boundaries"}
];

function getReferendumDesc(race) {
	for (var x=0;x<ref.length;x++) {
		if (ref[x].race == race)
			return ref[x].desc;
	}
	return "";
}

